#!/usr/bin/env bash

# Vars
REDIS_CONF=$(<redis.conf)
REDIS_CONF_PATH='/etc/redis/redis.conf'

# Figure out PHP Version from php-version or override-php-version in this repo's root config/versions
PHP_VERSION=$(<../../../config/versions/php-version)
if [ -f "../../../config/versions/override-php-version" ]; then
    PHP_VERSION=$(<../../../config/versions/override-php-version)
fi

# Update
sudo apt update

# Install
sudo apt-get -y install redis-server

# Enable
sudo systemctl enable redis-server.service

# Add the Config
if [ -f "$REDIS_CONF_PATH" ]; then
    # replace/create file
    echo "$REDIS_CONF" >> "$REDIS_CONF_PATH"
else
    # append to file
    echo "$REDIS_CONF" > "$REDIS_CONF_PATH"
fi

# Restart
sudo systemctl restart redis-server.service

# Add php redis depending on PHP_VERSION
sudo apt-get install -y php"$PHP_VERSION"-redis

# Test it with: redis-cli
# Default host:port - 127.0.0.1:6379