#!/usr/bin/env bash

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

source ~/.bashrc

command -v nvm

# usage: nvm install 6.4.1

cat /var/www/LEMP-setup-guide/install/components/nvm/shell-envs > ~/.bashrc

. ~/.nvm/nvm.sh
. ~/.profile
. ~/.bashrc