#!/usr/bin/env bash

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

source ~/.bashrc

command -v nvm

nvm install 10.14.2

cat /var/www/LEMP-setup-guide/install/components/nvm/shell-envs > ~/.bash_profile

source ~/.bash_profile

# . ~/.nvm/nvm.sh
# . ~/.profile
# . ~/.bashrc