#!/usr/bin/env bash

# run any other files that get put in this same folder.
WHERE=$(pwd)

chmod +x "$WHERE/scripts"

WHERE="$WHERE/scripts/*.sh"

for f in $WHERE; do  # or wget-*.sh instead of *.sh
  bash "$f" -H  || break # if needed 
done