#!/usr/bin/env bash

# run any other files that get put in this same folder.
WHERE=$(pwd)

WHERE="$WHERE/scripts/*.sh"

chmod +x "$WHERE"

for f in $WHERE; do  # or wget-*.sh instead of *.sh
  bash "$f" -H  || break # if needed 
done