#!/usr/bin/env bash
cr=`echo $'\n.'`
cr=${cr%.}

# Check if /var/www exists
if [ ! -d "/var/www" ]; then  
    mkdir /var/www/
fi

printf "Installing git...\n"
sudo apt-get install -y git

THIS_REPO=https://github.com/amurrell/LEMP-setup-guide.git

cd /var/www/

# Check if /var/www exists
if [ ! -d "/var/www/LEMP-setup-guide/" ]; then  
    git clone $THIS_REPO
fi

cd LEMP-setup-guide/scripts

./server-initial-setup.sh